adds all assessments
learn-academy-2023-golf/week-3-assessment-lilGuzi pull request #1
Opened 2023-10-24 00:10 UTC by lilGuzi

# Submitting Week 3 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [x] Behavioral Questions
- [x] Career Readiness
- [x] Coding Challenges
- [x] Interview Questions
- [x] React Debugging

### ✋ Reminder

Do NOT merge your assessment!

### 📝 Feedback

If you would like specific feedback please leave details here:

2023-10-25 18:27 UTC, chrisyhlee requested changes
You need to submit an attempt for code challenge 2. You also need to answer your looking ahead terms in the interview questions file. You were getting the error that made you give up because of line 3 in the code-challenges file, whenever that appears, you need to comment it out or delete it. From the work I'm seeing, this assessment displays Complete. Your pseudo code in challenge 1 is incomplete. As for the code, you are trying to call your function within the function itself. I suggest revisiting weeks 1 - 3 of class material in order to study the fundamentals. Your interview question answers are also bare minimum. Make the changes I mentioned earlier and then resubmit in order to be approved.

2023-10-25 18:27 UTC, chrisyhlee commented on code-challenges.test.js
> +// i Give up on this challenege, sunday oct 22 10:22pm  i keep gettin "your test suite must conatin at least one test" in terminal.
Look at line 3 in this file, you need to comment that out or delete it.

2023-10-25 18:27 UTC, chrisyhlee commented on code-challenges.test.js
> +// use
This pseudo code is incomplete

2023-10-27 17:39 UTC, elysemontano approved these changes

2023-10-27 18:02 UTC, merged